# Shared config for the FINS demo suite. One Unity Catalog schema, generated by
# `generate_data.py`, that every use-case folder reads from:
#   - agents/               (Knowledge Assistant + Supervisor + custom RAG)
#   - governance/           (AI Gateway + guardrails + MCP + observability)
#   - ai_runtime/           (Ray on serverless + LoRA fine-tune for triage)
#   - document_intelligence/(parse -> extract -> evaluate on the insurance PDFs)
#
# To adapt to another discipline: point CATALOG/SCHEMA at your own, and swap the
# generators in generate_data.py for your domain (keep the table/column shape).

CATALOG = "shm_skunkworks_catalog"    # <- change to your catalog
SCHEMA = "claims_demo"                # <- change to your schema
VOLUME = "docs"                       # knowledge docs (policy wordings, guidelines) for the KA/RAG
VOLUME_PATH = f"/Volumes/{CATALOG}/{SCHEMA}/{VOLUME}"
PDF_VOLUME = "raw_pdfs"               # real public insurance PDFs for document_intelligence
PDF_VOLUME_PATH = f"/Volumes/{CATALOG}/{SCHEMA}/{PDF_VOLUME}"

# Tables
CLAIMS_TABLE = f"{CATALOG}.{SCHEMA}.claims"           # structured claims -> Genie, PII guardrails, FT labels
NOTES_TABLE = f"{CATALOG}.{SCHEMA}.claim_notes"       # free-text adjuster notes -> RAG / FT text
CHUNKS_TABLE = f"{CATALOG}.{SCHEMA}.doc_chunks"       # chunked knowledge docs -> Vector Search source
VS_INDEX = f"{CATALOG}.{SCHEMA}.doc_chunks_index"     # Vector Search index (Delta Sync)

# Foundation models (serverless, pay-per-token -- confirmed available on the FEVM)
CHAT_MODEL = "databricks-claude-sonnet-4-5"
EMBED_MODEL = "databricks-gte-large-en"
EMBED_DIM = 1024

# Vector Search endpoint -- dedicated endpoint for the claims demo (avoids sharing
# compute with the large pre-existing index on the shared `vs` endpoint)
VS_ENDPOINT = "claims_vs"

# Scale (kept small on purpose -- "simple but showcases the platform")
N_CLAIMS = 2000
SEED = 42
